platform :ios, ‘7.1’
#use_frameworks!

target 'H2HSDKIntegrationSample' do

  pod 'KissXML'
  pod  'CocoaAsyncSocket'
  pod 'CocoaLumberjack’, ‘2.2.0’
  pod 'Firebase/Core'
  pod 'Firebase/Database'

end